# Generated by Django 4.2.6 on 2023-10-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="web_site",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
