# Generated by Django 4.2.6 on 2023-10-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="order",
            field=models.IntegerField(default="1"),
            preserve_default=False,
        ),
    ]
